require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./models/User');
const Faculty = require('./models/Faculty');

const MONGO_URI = process.env.MONGO_URI || 'mongodb+srv://vasudevcs037_db_user:iqac123@iqac.thi9ynv.mongodb.net/?appName=iqac';

const seedProfiles = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    const username1 = 'dr_john_doe';
    const email1 = 'john.doe@university.edu';

    const username2 = 'dr_jane_smith';
    const email2 = 'jane.smith@university.edu';

    // Cleanup existing mock data
    await User.deleteMany({ username: { $in: [username1, username2] } });
    await Faculty.deleteMany({ username: { $in: [username1, username2] } });

    const user1 = await User.create({
      username: username1,
      email: email1,
      password: 'password123',
      role: 'faculty',
      isActive: true,
      isFirstLogin: false
    });

    const user2 = await User.create({
      username: username2,
      email: email2,
      password: 'password123',
      role: 'faculty',
      isActive: true,
      isFirstLogin: false
    });

    const docUrl = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';
    const photoUrl = 'https://randomuser.me/api/portraits/men/32.jpg';
    const photoUrl2 = 'https://randomuser.me/api/portraits/women/44.jpg';

    const getFaculty1Data = (userId) => ({
      userId: userId,
      username: username1,
      profileComplete: true,
      completionPercentage: 100,
      personalInfo: {
        firstName: 'John',
        middleName: 'William',
        lastName: 'Doe',
        fullName: 'Dr. John William Doe',
        dateOfBirth: '1980-05-15',
        gender: 'Male',
        bloodGroup: 'O+',
        nationality: 'Indian',
        permanentAddress: '123 MG Road, Apt 4B',
        permanentState: 'Maharashtra',
        permanentCity: 'Mumbai',
        permanentPin: '400001',
        currentAddress: 'University Campus, Qtr 12',
        currentState: 'Maharashtra',
        currentCity: 'Mumbai',
        currentPin: '400098',
        stateAndCity: 'Maharashtra - Mumbai',
        mobilePersonal: '9876543210',
        alternatePhone: '9876543211',
        officialEmail: email1,
        personalEmail: 'john.personal@gmail.com',
        professionalHeadline: 'Professor of Computer Science',
        biography: 'Experienced professor with 15+ years in teaching and research in AI.',
        subjects: 'Artificial Intelligence, Machine Learning',
        interests: 'Deep Learning, NLP',
        age: '46',
        community: 'General',
        fatherName: 'Robert Doe',
        motherName: 'Mary Doe',
        communicationAddress: 'University Campus, Qtr 12',
        communicationCity: 'Mumbai',
        communicationState: 'Maharashtra',
        communicationPin: '400098',
        mobileNumber: '9876543210',
        alternateMobileNumber: '9876543211',
        officialEmailId: email1,
        personalEmailId: 'john.personal@gmail.com',
        emergencyContactNumber: '9876543211',
        aadhaarNumber: '123456789012',
        passportNumber: 'Z1234567',
        panNumber: 'ABCDE1234F',
        religion: 'Hinduism',
        category: 'General',
        subCategory: 'None',
        differentlyAbled: 'No',
        disabilityType: '',
        maritalStatus: 'Married',
        spouseName: 'Sarah Doe',
        spouseOccupation: 'Teacher',
        emergencyContactName: 'Sarah Doe',
        emergencyContactMobile: '9876543211',
        photoUrl: photoUrl,
        orcidId: '0000-0002-1825-0097',
        googleScholarId: 'abc123xyz',
        scopusId: '987654321',
        linkedIn: 'https://linkedin.com/in/johndoe',
        website: 'https://johndoe.com'
      },
      qualifications: [{
        degreeLevel: 'Ph.D',
        degreeName: 'Ph.D in Computer Science',
        specialization: 'Artificial Intelligence',
        institution: 'IIT Bombay',
        university: 'IIT Bombay',
        boardUniversity: 'IIT Bombay',
        yearOfPassing: '2010',
        gradeType: 'CGPA',
        percentageCGPA: '9.2',
        division: 'First',
        mode: 'Regular',
        country: 'India',
        state: 'Maharashtra',
        countryAndState: 'India - Maharashtra',
        phdCertificate: '12345',
        thesisTitle: 'Deep Learning for NLP',
        documentUrl: docUrl
      }, {
        degreeLevel: 'PG',
        degreeName: 'M.Tech',
        specialization: 'Computer Science',
        institution: 'NIT Trichy',
        university: 'NIT Trichy',
        boardUniversity: 'NIT Trichy',
        yearOfPassing: '2005',
        gradeType: 'CGPA',
        percentageCGPA: '8.8',
        division: 'First',
        mode: 'Regular',
        country: 'India',
        state: 'Tamil Nadu',
        countryAndState: 'India - Tamil Nadu',
        phdCertificate: '',
        thesisTitle: '',
        documentUrl: docUrl
      }],
      eligibilityTests: [{
        examName: 'NET',
        subject: 'Computer Science',
        year: '2006',
        certificateNo: 'NET12345',
        score: '65',
        state: '',
        fellowshipAgency: 'UGC',
        validityStatus: 'Lifetime',
        documentUrl: docUrl
      }],
      employmentDetails: {
        employeeId: 'EMP001',
        designation: 'Professor',
        department: 'Computer Science',
        institution: 'University of Mumbai',
        affiliatedUniversity: 'University of Mumbai',
        dateOfAppointment: '2015-08-01',
        natureOfAppointment: 'Regular',
        approvalOfAppointment: 'Yes',
        approvalLetterNo: 'APP/2015/123',
        approvalLetterDate: '2015-07-25',
        scaleOfPay: 'Level 14',
        currentBasicPay: '144200',
        totalExperienceYears: '15',
        totalExperienceMonths: '2',
        dateOfRetirement: '2045-05-15'
      },
      workExperience: [{
        organization: 'TCS Innovation Labs',
        designation: 'Research Scientist',
        from: '2010-06-01',
        to: '2015-07-31',
        nature: 'Research',
        reasonForLeaving: 'To join academics',
        employeeId: 'TCS123',
        department: 'R&D',
        institution: 'TCS',
        affiliatedUniversity: '',
        typeOfInstitution: 'Industry',
        natureOfAppointment: 'Regular',
        documentUrl: docUrl
      }],
      publications: [{
        type: 'Journal Articles',
        title: 'Advances in Deep Learning for NLP',
        authors: 'John Doe, Alice Smith',
        authorRole: 'Principal',
        journal: 'IEEE Transactions on Neural Networks',
        journalCategory: 'Q1',
        year: '2022',
        volume: '33',
        issue: '4',
        issn: '1045-9227',
        isbn: '',
        pages: '1023-1035',
        impactFactor: '10.4',
        indexedIn: 'Scopus',
        peerReviewed: 'Yes',
        doi: '10.1109/TNNLS.2022.1234567',
        level: 'International',
        presentationType: '',
        venue: '',
        conferenceDates: '',
        documentUrl: docUrl,
        editors: '',
        bookType: '',
        organizedBy: '',
        publishedInProceedings: ''
      }],
      awards: [{
        name: 'Best Researcher Award',
        awardingAgency: 'IEEE India',
        dateOfAward: '2021-12-15',
        yearReceived: '2021',
        level: 'National',
        awardCategory: 'Research',
        honourType: 'Award',
        recognitionStatus: 'Recognized'
      }],
      projects: [{
        title: 'AI for Healthcare Diagnostics',
        fundingAgency: 'DST',
        projectCategory: 'Major',
        fundingType: 'Government',
        amountSanctioned: '5000000',
        startDate: '2019-04-01',
        endDate: '2022-03-31',
        status: 'Completed',
        role: 'PI',
        referenceNumber: 'DST/AI/2019/01'
      }],
      patents: [{
        title: 'System and method for intelligent text summarization',
        patentNumber: 'IN123456',
        dateOfFiling: '2020-01-15',
        status: 'Granted',
        patentType: 'Utility'
      }],
      researchGuidance: {
        phdCompleted: '2',
        phdInProgress: '4',
        mphilCompleted: '1',
        mphilInProgress: '0',
        pgProjectsSupervised: '15',
        completedStudentsNames: 'Mark Taylor, Linda Brown',
        studentDetails: [{
          studentName: 'Mark Taylor',
          topic: 'Transformers in NLP',
          year: '2021',
          fellowship: 'JRF',
          degree: 'Ph.D.',
          status: 'Completed',
          scholarGender: 'Male',
          guidanceType: 'Principal Guide',
          supervisionCategory: 'Ph.D.'
        }]
      },
      adminResponsibilities: [{
        committeeName: 'Board of Studies',
        role: 'Chairman',
        from: '2020-08-01',
        to: '2023-07-31'
      }],
      fdpWorkshops: [{
        programTitle: 'Recent Trends in AI',
        type: 'FDP',
        organizingInstitution: 'NIT Warangal',
        duration: '1 Week',
        from: '2022-05-10',
        to: '2022-05-16',
        mode: 'Online',
        certificate: 'Yes',
        year: '2022',
        documentUrl: docUrl
      }],
      onlineCourses: [{
        courseName: 'Machine Learning by Andrew Ng',
        platform: 'Coursera',
        duration: '11 Weeks',
        completionYear: '2018',
        from: '2018-01-01',
        to: '2018-03-15',
        certificateId: 'COURSERA123',
        certificateUrl: docUrl,
        score: '98',
        courseLevel: 'Intermediate'
      }],
      memberships: [{
        professionalBody: 'IEEE',
        membershipType: 'Senior Member',
        membershipId: '98765432',
        yearOfJoining: '2010',
        documentUrl: docUrl
      }],
      internationalExperience: [{
        country: 'USA',
        purpose: 'Visiting Scholar',
        institution: 'MIT',
        duration: '6 Months',
        from: '2017-01-01',
        to: '2017-06-30',
        fundingSource: 'Fulbright'
      }],
      qualityAssurance: [{
        administrativeCharge: 'IQAC Member',
        academicYear: '2022-2023',
        activityTitle: 'NAAC Preparation',
        activityDate: '2023-01-10',
        activityCategory: 'Meeting',
        objective: 'Prepare SSR',
        outcome: 'Draft SSR Completed',
        supportingDocuments: docUrl,
        remarks: 'Excellent progress',
        criteriaNumber: '3',
        criteriaName: 'Research, Innovations and Extension',
        taskDescription: 'Compile research data',
        evidenceAvailable: 'Yes',
        status: 'Completed',
        reportName: 'Criterion 3 Report',
        reportingPeriod: '2022-23',
        preparedBy: 'John Doe',
        criteriaCovered: '3.1 to 3.5',
        reviewDate: '2023-02-15',
        reviewedBy: 'IQAC Coordinator',
        reportStatus: 'Approved',
        departmentName: 'Computer Science',
        coordinatorName: 'Jane Smith',
        facultyDataSubmitted: 'Yes',
        studentDataSubmitted: 'Yes',
        researchDataSubmitted: 'Yes',
        submissionStatus: 'Submitted',
        reportCycle: '1',
        dataCategory: 'Research',
        verifiedBy: 'Principal',
        verificationDate: '2023-03-01',
        studentStrength: '120',
        facultyStrength: '15',
        publicationCount: '45',
        placementDataSubmitted: 'Yes',
        semester: 'Even',
        feedbackType: 'Student Feedback',
        feedbackSummary: 'Very Good',
        actionPlan: 'Improve lab facilities',
        responsiblePerson: 'HOD',
        implementationStatus: 'In Progress',
        responsibilityTitle: 'IQAC Member',
        startDate: '2021-07-01',
        endDate: '2024-06-30',
        description: 'Coordinate quality initiatives'
      }],
      departmentalCharges: [{
        administrativeCharge: 'HOD',
        institutionName: 'University of Mumbai',
        departmentName: 'Computer Science',
        committeeName: 'Departmental Committee',
        libraryName: '',
        role: 'Chairman',
        responsibilities: 'Manage department affairs',
        activitiesCoordinated: 'All academic activities',
        mentoringScheme: 'Yes',
        numberOfStudents: '120',
        academicYear: '2023-2024',
        eventTitle: 'Tech Fest',
        eventType: 'Festival',
        organizingDepartment: 'Computer Science',
        eventDate: '2024-02-10',
        title: 'Head of Department',
        description: 'Overall charge of the department',
        appointmentDate: '2022-07-01',
        tenureStart: '2022-07-01',
        tenureEnd: '2025-06-30',
        remarks: ''
      }],
      specialAssignments: [{
        administrativeCharge: 'NSS Officer',
        organizationName: 'University of Mumbai',
        programName: 'NSS',
        cellName: 'NSS Cell',
        nssUnitNumber: 'Unit 1',
        nccUnitName: '',
        role: 'Program Officer',
        roleDescription: 'Coordinate NSS activities',
        responsibilityArea: 'Community Service',
        activityType: 'Camp',
        activitiesConducted: 'Blood Donation, Cleanliness Drive',
        placementActivities: '',
        platformName: '',
        communityPartner: 'Local NGO',
        title: 'NSS Program Officer',
        description: 'Lead NSS unit of the college',
        appointmentDate: '2021-08-01',
        tenureStart: '2021-08-01',
        tenureEnd: '2024-07-31',
        remarks: ''
      }],
      extraInstitutionalActivities: [{
        administrativeCharge: 'External Examiner',
        institutionName: 'Pune University',
        universityName: 'Pune University',
        organizationName: '',
        department: 'Computer Science',
        facultyName: 'Science and Technology',
        specialization: 'AI',
        programName: 'M.Sc. CS',
        courseName: 'Machine Learning',
        role: 'Examiner',
        nominationType: 'Academic',
        examinationType: 'Practical',
        title: 'External Practical Examiner',
        description: 'Conducted practical exams for M.Sc.',
        appointmentDate: '2023-11-15',
        tenureStart: '2023-12-01',
        tenureEnd: '2023-12-05',
        remarks: ''
      }],
      adminNonAcademicResponsibilities: [{
        administrativeCharge: 'Warden',
        institutionName: 'University of Mumbai',
        campusName: 'Main Campus',
        universityName: 'University of Mumbai',
        facultyName: 'Science',
        committeeName: 'Hostel Committee',
        title: 'Chief Warden',
        organization: 'University',
        nominationType: 'Administrative',
        reportingAuthority: 'Registrar',
        appointingAuthority: 'Vice Chancellor',
        responsibilities: 'Manage boys hostel',
        activitiesConducted: 'Hostel Day, Sports meet',
        departmentAssigned: 'Student Welfare',
        description: 'Overall supervision of the hostel',
        admissionYear: '2023',
        appointmentDate: '2022-01-01',
        tenureStart: '2022-01-01',
        tenureEnd: '2025-12-31',
        remarks: ''
      }],
      academicAdministration: [{
        administrativeCharge: 'Member BOS',
        programDepartment: 'Computer Science',
        constitutedBy: 'Vice Chancellor',
        syllabusCourse: 'B.Sc. CS',
        departmentProgram: 'Computer Science',
        academicSession: '2023-2024',
        focusArea: 'Syllabus Revision',
        examRole: 'Paper Setter',
        examination: 'TY B.Sc.',
        board: 'BOS Computer Science',
        meetingDate: '2023-09-15',
        councilBody: 'Academic Council',
        department: 'Computer Science',
        reviewType: 'Annual',
        title: 'Member, Board of Studies',
        departmentUnit: 'Computer Science',
        description: 'Participated in syllabus design',
        appointmentDate: '2022-06-01',
        from: '2022-06-01',
        to: '2025-05-31',
        remarks: ''
      }],
      researchAndInnovation: [{
        administrativeCharge: 'Research Coordinator',
        departmentSchoolCenter: 'Computer Science',
        departmentUnit: 'Research Cell',
        organizingDepartmentUnit: 'Research Cell',
        fundingAgencyOrganization: 'UGC',
        typeOfProposal: 'Research Grant',
        typeOfFunding: 'Government',
        projectSchemeName: 'STRIDE',
        roleResponsibility: 'Coordinator',
        areasOfResearchCoordinated: 'AI, ML, Data Science',
        conferenceEventName: 'International Conference on AI',
        keyResponsibilities: 'Organize conference',
        title: 'Research Cell Coordinator',
        description: 'Coordinate all research activities in the department',
        appointmentDate: '2021-07-01',
        from: '2021-07-01',
        to: '2024-06-30',
        remarks: ''
      }],
      examinationAndEvaluation: [{
        administrativeCharge: 'Chief Conductor',
        institutionName: 'University of Mumbai',
        departmentName: 'Exam Cell',
        boardName: 'University Exam Board',
        courseName: 'All UG/PG',
        subjectArea: 'General',
        examinationSession: 'Winter 2023',
        activityType: 'Exam Conduction',
        roleDescription: 'Conduct exams smoothly',
        coursesManaged: 'B.Sc, M.Sc, B.Com, B.A.',
        examinationSessionsHandled: 'Morning and Afternoon',
        responsibilities: 'Overall charge of examination center',
        title: 'Chief Conductor of Examinations',
        description: 'Managed the winter 2023 examinations for the college center',
        contributionDate: '2023-11-20',
        appointmentDate: '2023-10-01',
        tenureStart: '2023-11-15',
        tenureEnd: '2023-12-30',
        remarks: ''
      }],
      administrativeSupport: [{
        administrativeCharge: 'Nodal Officer',
        departmentUnit: 'Scholarship Section',
        roleResponsibility: 'Verify scholarship forms',
        attendanceSystemMethod: 'Biometric',
        workloadType: 'Administrative',
        areaOfResponsibility: 'MahaDBT Portal',
        areaOfEnforcement: 'College level',
        responsibilityTitle: 'Nodal Officer for Scholarships',
        descriptionOfResponsibility: 'Verification of state and national scholarships',
        appointmentDate: '2020-08-01',
        tenureStart: '2020-08-01',
        tenureEnd: '2025-07-31',
        remarks: ''
      }],
      documents: {
        photo: photoUrl,
        signature: docUrl,
        aadhar: docUrl,
        pan: docUrl,
        ssc: docUrl,
        hsc: docUrl,
        ug: docUrl,
        pg: docUrl,
        phd: docUrl,
        mphil: docUrl,
        net: docUrl,
        gate: docUrl,
        apptLetter: docUrl,
        experienceCert: docUrl,
        publications: docUrl,
        noc: docUrl,
        casteCert: docUrl,
        disabilityCert: docUrl,
        dobProof: docUrl,
        nationalId: docUrl
      }
    });

    const getFaculty2Data = (userId) => ({
      userId: userId,
      username: username2,
      profileComplete: true,
      completionPercentage: 100,
      personalInfo: {
        firstName: 'Jane',
        middleName: 'Anne',
        lastName: 'Smith',
        fullName: 'Dr. Jane Anne Smith',
        dateOfBirth: '1985-10-20',
        gender: 'Female',
        bloodGroup: 'A+',
        nationality: 'Indian',
        permanentAddress: '456 MG Road',
        permanentState: 'Delhi',
        permanentCity: 'New Delhi',
        permanentPin: '110001',
        currentAddress: 'University Campus',
        currentState: 'Delhi',
        currentCity: 'New Delhi',
        currentPin: '110021',
        stateAndCity: 'Delhi - New Delhi',
        mobilePersonal: '9876543222',
        alternatePhone: '9876543223',
        officialEmail: email2,
        personalEmail: 'jane.personal@gmail.com',
        professionalHeadline: 'Associate Professor of Physics',
        biography: 'Passionate about quantum mechanics and teaching.',
        subjects: 'Quantum Physics, Mechanics',
        interests: 'Quantum Computing, Astrophysics',
        age: '41',
        community: 'General',
        fatherName: 'Michael Smith',
        motherName: 'Susan Smith',
        communicationAddress: 'University Campus',
        communicationCity: 'New Delhi',
        communicationState: 'Delhi',
        communicationPin: '110021',
        mobileNumber: '9876543222',
        alternateMobileNumber: '9876543223',
        officialEmailId: email2,
        personalEmailId: 'jane.personal@gmail.com',
        emergencyContactNumber: '9876543223',
        aadhaarNumber: '210987654321',
        passportNumber: 'Y1234567',
        panNumber: 'FGHIJ5678K',
        religion: 'Christianity',
        category: 'General',
        subCategory: 'None',
        differentlyAbled: 'No',
        disabilityType: '',
        maritalStatus: 'Single',
        spouseName: '',
        spouseOccupation: '',
        emergencyContactName: 'Michael Smith',
        emergencyContactMobile: '9876543223',
        photoUrl: photoUrl2,
        orcidId: '0000-0003-1234-5678',
        googleScholarId: 'xyz987abc',
        scopusId: '123456789',
        linkedIn: 'https://linkedin.com/in/janesmith',
        website: 'https://janesmith.com'
      },
      qualifications: [{
        degreeLevel: 'Ph.D',
        degreeName: 'Ph.D in Physics',
        specialization: 'Quantum Mechanics',
        institution: 'IISc Bangalore',
        university: 'IISc Bangalore',
        boardUniversity: 'IISc Bangalore',
        yearOfPassing: '2012',
        gradeType: 'CGPA',
        percentageCGPA: '9.5',
        division: 'First',
        mode: 'Regular',
        country: 'India',
        state: 'Karnataka',
        countryAndState: 'India - Karnataka',
        phdCertificate: '54321',
        thesisTitle: 'Quantum Entanglement',
        documentUrl: docUrl
      }],
      eligibilityTests: [{
        examName: 'GATE',
        subject: 'Physics',
        year: '2008',
        certificateNo: 'GATE12345',
        score: '85',
        state: '',
        fellowshipAgency: 'MHRD',
        validityStatus: 'Lifetime',
        documentUrl: docUrl
      }],
      employmentDetails: {
        employeeId: 'EMP002',
        designation: 'Associate Professor',
        department: 'Physics',
        institution: 'University of Delhi',
        affiliatedUniversity: 'University of Delhi',
        dateOfAppointment: '2016-09-01',
        natureOfAppointment: 'Regular',
        approvalOfAppointment: 'Yes',
        approvalLetterNo: 'APP/2016/456',
        approvalLetterDate: '2016-08-20',
        scaleOfPay: 'Level 13A',
        currentBasicPay: '131400',
        totalExperienceYears: '12',
        totalExperienceMonths: '5',
        dateOfRetirement: '2050-10-31'
      },
      workExperience: [],
      publications: [{
        type: 'Journal Articles',
        title: 'Quantum Computing and Cryptography',
        authors: 'Jane Smith, Bob Johnson',
        authorRole: 'Principal',
        journal: 'Physical Review Letters',
        journalCategory: 'Q1',
        year: '2023',
        volume: '130',
        issue: '10',
        issn: '0031-9007',
        isbn: '',
        pages: '102001',
        impactFactor: '8.6',
        indexedIn: 'WoS',
        peerReviewed: 'Yes',
        doi: '10.1103/PhysRevLett.130.102001',
        level: 'International',
        presentationType: '',
        venue: '',
        conferenceDates: '',
        documentUrl: docUrl,
        editors: '',
        bookType: '',
        organizedBy: '',
        publishedInProceedings: ''
      }],
      awards: [{
        name: 'Young Scientist Award',
        awardingAgency: 'DST',
        dateOfAward: '2018-02-28',
        yearReceived: '2018',
        level: 'National',
        awardCategory: 'Research',
        honourType: 'Award',
        recognitionStatus: 'Recognized'
      }],
      projects: [{
        title: 'Quantum Materials',
        fundingAgency: 'CSIR',
        projectCategory: 'Major',
        fundingType: 'Government',
        amountSanctioned: '3000000',
        startDate: '2020-04-01',
        endDate: '2023-03-31',
        status: 'Completed',
        role: 'PI',
        referenceNumber: 'CSIR/QM/2020'
      }],
      patents: [],
      researchGuidance: {
        phdCompleted: '1',
        phdInProgress: '2',
        mphilCompleted: '0',
        mphilInProgress: '0',
        pgProjectsSupervised: '10',
        completedStudentsNames: 'Emily White',
        studentDetails: [{
          studentName: 'Emily White',
          topic: 'Quantum Optics',
          year: '2022',
          fellowship: 'CSIR-JRF',
          degree: 'Ph.D.',
          status: 'Completed',
          scholarGender: 'Female',
          guidanceType: 'Principal Guide',
          supervisionCategory: 'Ph.D.'
        }]
      },
      adminResponsibilities: [],
      fdpWorkshops: [],
      onlineCourses: [],
      memberships: [{
        professionalBody: 'Indian Physics Association',
        membershipType: 'Life Member',
        membershipId: 'IPA123',
        yearOfJoining: '2015',
        documentUrl: docUrl
      }],
      internationalExperience: [],
      qualityAssurance: [],
      departmentalCharges: [],
      specialAssignments: [],
      extraInstitutionalActivities: [],
      adminNonAcademicResponsibilities: [],
      academicAdministration: [],
      researchAndInnovation: [],
      examinationAndEvaluation: [],
      administrativeSupport: [],
      documents: {
        photo: photoUrl2,
        signature: docUrl,
        aadhar: docUrl,
        pan: docUrl,
        ssc: docUrl,
        hsc: docUrl,
        ug: docUrl,
        pg: docUrl,
        phd: docUrl,
        mphil: docUrl,
        net: docUrl,
        gate: docUrl,
        apptLetter: docUrl,
        experienceCert: docUrl,
        publications: docUrl,
        noc: docUrl,
        casteCert: docUrl,
        disabilityCert: docUrl,
        dobProof: docUrl,
        nationalId: docUrl
      }
    });

    await Faculty.create(getFaculty1Data(user1._id));
    await Faculty.create(getFaculty2Data(user2._id));

    console.log('Successfully created 2 mock profiles.');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding profiles:', error);
    process.exit(1);
  }
};

seedProfiles();
